name: GHCR Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Github Package Repository
      run: echo ${{ secrets.GOOSE_BUILD }} | docker login ghcr.io -u ${{ secrets.GH_USER }} --password-stdin

    - name: Build and push image
      run: |
        docker build -t ghcr.io/sharegoapp/goose:latest .
        docker push ghcr.io/sharegoapp/goose:latest
      env:
        DOCKER_BUILDKIT: 1